name: docker-ci-pipeline
on:
  push:
    branches:
      - devsecops-jan-2025

jobs:
  build-sysfoo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Code Checkout or Code Clone
        uses: actions/checkout@v4
  
      - name: Docker login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build Step
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sysfoo:v1 .

      - name: Docker Push Step
        run: docker push ${{ secrets.DOCKER_USERNAME }}/sysfoo:v1   

      
