name: hello-world-cf
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps :
      - name: my-step
        run: echo "hello world!"
        
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@v2
        
      - name: SAST
        run: echo "SAST"
     

      - name: Docker Image
        run: docker build -t habeebr1972/cf-sysfoo .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
         image-ref: 'docker.io/habeebr1972/cf-sysfoo:latest'
         format: 'table'

      - name: DockerHub
        run: echo "DockerHub"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@v2
    
        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=habeeb1972key
            -Dsonar.projectKey=Habeeb1972_sysfoo
            -Dsonar.sources=.
            -Dsonar.verbose=true
            -Dsonar.language=java
            -Dsonar.java.binaries=./target/classes
  
          
      - name: DockerHub
        run: docker push habeebr1972/cf-sysfoo:latest
        
      - name: DAST - ZAP
        run: echo "DAST - ZAP"

      - name: DAST - ZAP
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://ginandjuice.shop/'
