name: sysfoo-ci-pipeline
on:
  push:
    branches:
      - devsecops-jan-2025

jobs:
  build-sysfoo:
    runs-on: windows-latest
    
    steps:
      - name: Code Checkout or Code Clone
        uses: actions/checkout@4

      - name: Run mvn test
        run: mvn test

      - name: Run mvn clean & mvn package
        run: mvn clean package

      - name: Run dir command
        run: dir

      

  
